ignore_layers: [] # ["speaker_emb"]

path:
  ckpt_path: "/scratch/space1/tc046/lordzuko/work/output/ckpt/BC2013_ref"
  log_path: "/scratch/space1/tc046/lordzuko/work/output/log/BC2013_ref"
  result_path: "/scratch/space1/tc046/lordzuko/work/output/result/BC2013_ref"

optimizer:
  batch_size: 50
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [30000, 40000, 50000]
  anneal_rate: 0.3
  init_lr: 0.0001
  anneal_lr: 0.001

step:
  total_step: 90000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 1000

loss:
  lambda_f: 0.001
  anneal_steps: 10000


